[meta]
# site title, show in <title>
title = "OpenHex"

# subtitle, words after title, in description
subtitle = "Just For Fun"

# print in html <meta>
keyword = "golang,c++,cloud storage,distributed system"

# print in html <meta>
desc = ""

# build links for feed, sitemap
domain = "openhex.cn"

# root path for site# if empty, build as http://{domain}/
root = ""

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "en"

# markdown code theme, seee https://prismjs.com/
prism_theme = "default"
# prism_theme = "okaidia"

[[nav]]
link = "/About"
title = "About"
i18n = "about"
hover = "about me"
blank = true

# [[nav]]
# link = "/docs"
# title = "Docs"
# i18n = "docs"
# hover = "docs"
# blank = true
# 
# [[nav]]
# link = "http://godoc.org/github.com/kdf5000/pugo"
# title = "API"
# i18n = "api"
# hover = "api"
# blank = true
# 
# [[nav]]
# link = "/news"
# title = "News"
# i18n = "news"
# hover = "news"
# blank = true

[[author]]
name = "KDF5000"
email = ""
url = "http://openhex.cn"
avatar = "@media/author.png"
bio = ""

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""

[build]
# disable_post disable to read & compile post data
disable_post = false
# disable_page disable to read & compile page data
disable_page = false
# post_dir set posts directory
post_dir = "post"
# page_dir set pages directory
page_dir = "page"
# media dir set media directory, based on source directory
media_dir = "media"
